package lookingawesomechatserver;

import java.util.Scanner;

public class Crypt1337{
	public static char[] encrypting(char[] text){			
		   int  u=0, o=text.length*4;
		   char[] temp=new char[o];
		   for(int i=0;i<text.length;i++)
		   {
				switch (text[i]){
					case 'a': 	temp[u] = '4' ;
								u++;
							break;
					case 'A': 	temp[u] = '4' ;
								u++;
							break;					
					case 'b': 	temp[u] = '8' ;
								u++;
							break;
					case 'B': 	temp[u] = '8' ;
								u++;
							break;					
					case 'c': 	temp[u] = '(' ;
								u++;
							break;
					case 'C': 	temp[u] = '(' ;
								u++;
							break;					
					case 'd': 	temp[u] = '|' ;
								u++;
								temp[u] = ')' ;
								u++;
							break;
					case 'D': 	temp[u] = '|' ;
								u++;
								temp[u] = ')' ;
								u++;
							break;					
					case 'e': 	temp[u] = '3' ;
								u++;
							break;
					case 'E': 	temp[u] = '3' ;
								u++;	
							break;				
					case 'f': 	temp[u] = 'F' ;
								u++;
								break;
					case 'F': 	temp[u] = 'F' ;
								u++;
							break;
					case 'g': 	temp[u] = '6' ;
								u++;
							break;
					case 'G': 	temp[u] = '6' ;
								u++;
							break;					
					case 'h': 	temp[u] = '|' ;
								u++;
								temp[u] = '-' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'H': 	temp[u] = '|' ;
								u++;
								temp[u] = '-' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'i': 	temp[u] = '|' ;
								u++;
							break;
					case 'I': 	temp[u] = '|' ;
								u++;
							break;
					case 'j': 	temp[u] = '_' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'J': 	temp[u] = '_' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'k': 	temp[u] = '|' ;
								u++;
								temp[u] = '<' ;
								u++;
							break;
					case 'K': 	temp[u] = '|' ;
								u++;
								temp[u] = '<' ;
								u++;
							break;
					case 'l': 	temp[u] = '1' ;
								u++;
							break;
					case 'L': 	temp[u] = '1' ;
								u++;
							break;
					case 'm': 	temp[u] = '|' ;
								u++;
								temp[u] = 'V' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'M': 	temp[u] = '|' ;
								u++;
								temp[u] = 'V' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'n': 	temp[u] = '/' ;
								u++;
								temp[u] = 'V' ;
								u++;
							break;
					case 'N': 	temp[u] = '/' ;
								u++;
								temp[u] = 'V' ;
								u++;
							break;
					case 'o': 	temp[u] = '0' ;
								u++;
							break;
					case 'O': 	temp[u] = '0' ;
								u++;
							break;
					case 'p': 	temp[u] = '|' ;
								u++;
								temp[u] = '°' ;
								u++;
							break;
					case 'P': 	temp[u] = '|' ;
								u++;
								temp[u] = '°' ;
								u++;
							break;
					case 'q': 	temp[u] = 'Q' ;
								u++;
							break;
					case 'Q': 	temp[u] = 'Q' ;
								u++;
							break;
					case 'r': 	temp[u] = 'R' ;
								u++;
							break;
					case 'R': 	temp[u] = 'R' ;
								u++;
							break;
					case 's': 	temp[u] = '5' ;
								u++;
							break;
					case 'S': 	temp[u] = '5' ;
								u++;
							break;
					case 't': 	temp[u] = '7' ;
								u++;
							break;
					case 'T': 	temp[u] = '7' ;
								u++;
							break;
					case 'u': 	temp[u] = '|' ;
								u++;
								temp[u] = '_' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'U': 	temp[u] = '|' ;
								u++;
								temp[u] = '_' ;
								u++;
								temp[u] = '|' ;
								u++;
							break;
					case 'v': 	temp[u] = 'V' ;
								u++;
							break;
					case 'V': 	temp[u] = 'V' ;
								u++;
							break;
					case 'w': 	temp[u] = 'V' ;
								u++;
								temp[u] = 'V' ;
								u++;
							break;
					case 'W': 	temp[u] = 'V' ;
								u++;
								temp[u] = 'V' ;
								u++;
							break;
					case 'x': 	temp[u] = '}' ;
								u++;
								temp[u] = '{' ;
								u++;
							break;
					case 'X': 	temp[u] = '}' ;
								u++;
								temp[u] = '{' ;
								u++;
							break;
					case 'y': 	temp[u] = 'Y' ;
								u++;
							break;
					case 'Y': 	temp[u] = 'Y' ;
								u++;
							break;
					case 'z': 	temp[u] = '2' ;
							u++;
							break;
					case 'Z': 	temp[u] = '2' ;
								u++;
	             		break;
	         		case 'ä':  	temp[u] = '4' ;
	         					u++;
	         					temp[u] = '3';
	         					u++;
	         			break;
	         		case 'Ä':  	temp[u] = '4' ;
	         					u++;
	         					temp[u] = '3';
	         					u++;
	         			break;
	         		case 'ö':  	temp[u] = '0' ;
	         					u++;
	         					temp[u] = '3';
	         					u++;
	         			break;
	         		case 'Ö':  	temp[u] = '0' ;
	         					u++;
	         					temp[u] = '3';
	         					u++;
	         			break;
	         		case 'ü':  	temp[u] = '|' ;
	         					u++;
	         					temp[u] = '_';
	         					u++;
	         					temp[u] = '|' ;
	         					u++;
	         					temp[u] = '3';
	         					u++;
	         			break;
	         		case 'Ü':  	temp[u] = '|' ;
								u++;
								temp[u] = '_';
								u++;
								temp[u] = '|' ;
								u++;
								temp[u] = '3';
								u++;
	         			break;
	         		case '.':  	temp[u] = ' ';
	         					u++;	
	         					temp[u] = 'S' ;
								u++;
								temp[u] = 't';
								u++;
								temp[u] = 'o' ;
								u++;
								temp[u] = 'p';
								u++;		
								temp[u] = ' ';
								u++;	
						break;
					default:    temp[u] = text[i];
								u++;
						break;
				}
			}
			return temp;
		}		
	public static String decrypting(String text){
	   	return text; 																
	 }			
	
	public static void main(String[] args){
    	String text;
        Scanner scanner = new Scanner(System.in);	
        char[] text2;
        
        System.out.println("Zu verschlüsselnden Text eingeben:");
        text=scanner.nextLine();
        text2=encrypting(text.toCharArray());
        
        System.out.println("Der Text sieht verschlüsselt so aus:");
        System.out.println(text);
        
        scanner.close();		 
	}
}